# Generated by Django 2.0.10 on 2019-07-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=49)),
                ('slug', models.SlugField(max_length=49, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('original', models.ImageField(upload_to='img')),
                ('thumbnail', models.ImageField(editable=False, upload_to='tmb')),
                ('caption', models.CharField(max_length=49)),
                ('text', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='article',
            name='image',
            field=models.ManyToManyField(blank=True, to='gallery.Image'),
        ),
    ]
