# Generated by Django 2.0.10 on 2019-07-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20190713_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='replies',
            field=models.ManyToManyField(related_name='_post_replies_+', to='gallery.Post'),
        ),
    ]
