# Generated by Django 2.0.10 on 2019-07-14 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_post_replies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='replies',
        ),
        migrations.AddField(
            model_name='post',
            name='replying_to',
            field=models.ManyToManyField(related_name='_post_replying_to_+', to='gallery.Post'),
        ),
    ]
