# Generated by Django 2.0.10 on 2019-07-14 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0005_auto_20190714_2258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reply',
            name='to',
        ),
        migrations.AddField(
            model_name='reply',
            name='from_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='from_post', to='gallery.Post'),
        ),
        migrations.AddField(
            model_name='reply',
            name='to_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='to_post', to='gallery.Post'),
        ),
    ]
