# Generated by Django 2.0.10 on 2019-07-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_auto_20190714_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reply',
            name='from_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='from_post', to='gallery.Post'),
        ),
    ]
